version: 2
updates:
    - package-ecosystem: gomod
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: "chore"
          include: "scope"
      labels:
          - dependencies
          - dependabot
          - go
      rebase-strategy: auto
      open-pull-requests-limit: 10
      groups:
          gomod:
              patterns:
                  - "*"
      reviewers:
          - "nicconike"

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: "ci"
      labels:
          - dependencies
          - dependabot
          - github_actions
      rebase-strategy: auto
      open-pull-requests-limit: 10
      reviewers:
          - "nicconike"
      groups:
          github-actions:
              patterns:
                  - "*"

    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "build"
          include: "scope"
      labels:
          - dependencies
          - dependabot
          - docker
      rebase-strategy: auto
      open-pull-requests-limit: 10
      groups:
          docker:
              patterns:
                  - "*"
      reviewers:
          - "nicconike"
