version: 2
updates:
    - package-ecosystem: gomod
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: "chore"
          include: "scope"
      labels:
          - dependencies
          - dependabot
      rebase-strategy: auto
      versioning-strategy: "increase-if-necessary"
      open-pull-requests-limit: 20
      reviewers:
          - "nicconike"

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: "ci"
      labels:
          - dependencies
          - dependabot
      rebase-strategy: auto
      open-pull-requests-limit: 20
      reviewers:
          - "nicconike"
      groups:
          github-actions:
              patterns:
                  - "*"
