run:
    timeout: 1m
output:
    formats:
        - format: colored-line-number
          path: stdout
linters:
    enable:
        - errcheck
        - gofmt
        - staticcheck
        - go_vet
        - gocyclo
        - ineffassign
        - license
        - misspell
