run:
    timeout: 1m
output:
    formats:
        - format: colored-line-number
          path: stdout
linters:
    enable:
        - errcheck
        - gofmt
        - staticcheck
        - gocyclo
        - ineffassign
        - misspell
linters-settings:
    gofmt:
        simplify: true
