project_name: AutomatedGo

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
      goarch:
          - amd64
      main: ./cmd/AutomatedGo

archives:
    - format: tar.gz
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      format_overrides:
          - goos: windows
            format: zip

changelog:
    sort: asc
    groups:
        - title: Features
          regexp: "^.*feat[(\\w)]*:+.*$"
          order: 0
        - title: "Bug Fixes"
          regexp: "^.*fix[(\\w)]*:+.*$"
          order: 1
        - title: Others
          order: 999

release:
    github:
        owner: Nicconike
        name: AutomatedGo
    prerelease: auto
    draft: false
    footer: |
        ## How to install
        ```
        go get -u github.com/Nicconike/AutomatedGo
        ```

        For more information, please refer to the [documentation](https://github.com/Nicconike/AutomatedGo#readme).

signs:
    - artifacts: checksum
