version: 2
project_name: AutomatedGo

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
      goarch:
          - amd64
      main: ./cmd/AutomatedGo

archives:
    - format: tar.gz
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      format_overrides:
          - goos: windows
            format: zip

changelog:
    use: github
    filters:
        exclude:
            - "^chore:"

release:
    github:
        owner: Nicconike
        name: AutomatedGo
    prerelease: auto
    draft: false
    footer: |
        ## How to install
        ```
        go install github.com/Nicconike/AutomatedGo/v2/cmd/automatedgo@v2.1.0
        ```

        For more information, please refer to the [documentation](https://github.com/Nicconike/AutomatedGo#readme).

signs:
    - artifacts: checksum
