version: 2
project_name: AutomatedGo

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
      goarch:
          - amd64
      main: ./cmd/AutomatedGo
      flags:
          - -trimpath

archives:
    - format: binary
      name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
    name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

changelog:
    use: github
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - "^chore:"

dockers:
    - dockerfile: Dockerfile
      image_templates:
          - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/AutomatedGo:{{ .Version }}"
          - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/AutomatedGo:master"
          - "{{ .Env.DOCKER_USERNAME }}/automatedgo:{{ .Version }}"
          - "{{ .Env.DOCKER_USERNAME }}/automatedgo:master"
      build_flag_templates:
          - "--label=org.opencontainers.image.created={{.Date}}"
          - "--label=org.opencontainers.image.title={{.ProjectName}}"
          - "--label=org.opencontainers.image.revision={{.FullCommit}}"
          - "--label=org.opencontainers.image.version={{.Version}}"

docker_signs:
    - cmd: cosign
      args:
          - "sign"
          - "${artifact}"
          - "--yes"
      artifacts: all
      output: true

signs:
    - cmd: cosign
      args:
          - "sign-blob"
          - "--output-signature=${signature}"
          - "${artifact}"
          - "--yes"
      artifacts: checksum

release:
    github:
        owner: Nicconike
        name: AutomatedGo
    prerelease: auto
    draft: false
    footer: |
        ## How to install
        ```
        go install github.com/Nicconike/AutomatedGo/v2/cmd/automatedgo@{{ .Tag }}
        ```

        For more information, please refer to the [documentation](https://github.com/Nicconike/AutomatedGo#readme).
