commitFormat: angular
branch:
    master: release
release: "github"
github:
    repo: "Nicconike/goautomate"
    user: "Nicconike"
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/github"
    - "@semantic-release/changelog"
    - - "@semantic-release/exec"
      - prepareCmd: "go mod tidy"
    - - "@semantic-release/git"
      - assets: ["go.mod", "go.sum", "CHANGELOG.md"]
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
