commitFormat: angular
branch:
    master: release
release: "github"
github:
    repo: "Nicconike/goautomate"
    user: "Nicconike"
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/changelog"
      - changelogFile: "CHANGELOG.md"
        changelogTitle: "# CHANGELOG"
    - "@semantic-release/github"
    - - "@semantic-release/git"
      - assets:
            - CHANGELOG.md
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
