name: "Code Coverage"

on:
    push:
        branches: master
    pull_request:
        branches: master

jobs:
    code-coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Setup Go
            uses: actions/setup-go@v5
            with:
                go-version: "1.22.x"

          - name: Install Dependencies
            run: go mod tidy

          - name: Run tests with coverage
            run: |
                cd tests/unit
                go test -v -race -coverprofile=coverage.txt -covermode=atomic checker_test.go config_test.go version_test.go

          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@v4.0.1
            with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: ./coverage.txt
                flags: unittests
                name: codecov-umbrella
                fail_ci_if_error: true
                verbose: true
