name: Release
on:
    push:
        branches: master

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - name: Setup Go
            uses: actions/setup-go@v5
            with:
                go-version: "1.22.x"
          - name: Run Semantic Release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                go install github.com/go-semantic-release/semantic-release@latest
                semantic-release
