name: Release
on:
    push:
        branches: master

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        permissions:
            contents: write
            packages: write
        steps:
          - name: GitHub App Token
            uses: actions/create-github-app-token@v1
            id: app-token
            with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.APP_PRIVATE_KEY }}

          - name: Checkout Repo
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
                token: ${{ steps.app-token.outputs.token }}

          - name: Setup Go
            uses: actions/setup-go@v5
            with:
                go-version: "1.22.x"

          - name: Run Semantic Release
            uses: go-semantic-release/action@v1
            id: semrel
            with:
                github-token: ${{ steps.app-token.outputs.token }}
                changelog-file: CHANGELOG.md
                update-file: go.mod
                changelog-generator-opt: "emojis=true"

          - name: Run GoReleaser
            uses: goreleaser/goreleaser-action@v4
            if: steps.semrel.outputs.version != ''
            with:
                distribution: releaser
                version: latest
                args: release --clean
            env:
                GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                GORELEASER_CURRENT_TAG: ${{ steps.semrel.outputs.version }}

          - name: Update pkg.go.dev
            if: steps.semrel.outputs.version != ''
            run: |
                go list -m github.com/Nicconike/goautomate@${{ steps.semrel.outputs.version }}
